name = "tracker-worker"
main = "src/index.ts"
compatibility_date = "2024-03-20"

[[d1_databases]]
binding = "DB"
database_name = "trackerv1"
database_id = "7fa13c09-c795-445a-a44c-ec3cf1fe1033"

[vars]
TELEMETRY_SECRET = "fox_telemetry_sec_8a3f9e2b1c7d4e5a9b0c2d3e4f5a6b7c"